name: Daily Runner

on:
    schedule:
        - cron: "15 22 * * *" # every day at 22:15 UTC

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Run script
              shell: bash
              env:
                  FROM_CHANNEL_ID: ${{ secrets.FROM_CHANNEL_ID }}
                  TO_CHANNEL_ID: ${{ secrets.TO_CHANNEL_ID }}
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
              run: |
                  pip3 install -r requirements.txt
                  python3 bot_slack.py
